version: 2.1
orbs:
  node: circleci/node@1.1.6

commands:
  restore_caches:
    description: 'Restore node_modules/, src/ and other files'
    steps:
      - restore_cache:
          keys:
            - '{{ .Branch }}-{{ .Revision }}'
      - restore_cache:
          keys:
            - '{{ .Branch }}-{{ checksum "yarn.lock" }}'

jobs:
  install-dependencies:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - '{{ .Branch }}-{{ checksum "yarn.lock" }}'
      - run: yarn
      - save_cache:
          key: '{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: 
            - node_modules
      - save_cache:
          key: '{{ .Branch }}-{{ .Revision }}'
          paths:
            - src
            - yarn.lock
            - package.json
            - audit-ci.json
            - jest.config.js
            - tsconfig.json
            - .eslintrc.js
  compile:
    executor:
      name: node/default
    steps:
      - restore_caches
      - run: yarn build-ts
          
  test-unit:
    executor:
      name: node/default
    steps:
      - restore_caches
      - run: yarn test

  lint:
    executor:
      name: node/default
    steps:
      - restore_caches
      - run: yarn lint-strict

  audit-dependencies:
    executor:
      name: node/default
    steps:
      - restore_caches
      - run: yarn audit-dependencies
  
  publish-dryrun:
    executor:
      name: node/default
    steps:
      - restore_caches
      - run: |
          npm pack
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish $(ls *.tgz) --dryrun

  publish:
    executor:
      name: node/default
    steps:
      - restore_caches
      - run: |
          npm pack
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish $(ls *.tgz)

workflows:
    standard-build:
      jobs:
        - install-dependencies
        - compile:
            requires: [install-dependencies]
        - test-unit:
            requires: [install-dependencies]
        - lint:
            requires: [install-dependencies]
        - audit-dependencies:
            requires: [install-dependencies]
        - publish-dryrun:
            requires: [compile]
        - publish:
            requires:
              - compile
              - test-unit
              - lint
              - audit-dependencies
              - publish-dryrun
            filters:
              branches:
                only:
                  - master
